const DATA={core:null,reforms:null,regions:null,votes:null,partners:null,legal:null};
const VER='20260901-v54';
const $=id=>document.getElementById(id);
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function getJSON(path){const r=await fetch(path+'?v='+VER);if(!r.ok)throw new Error(path+' · HTTP '+r.status);return r.json()}
function route(){const raw=(location.hash||'#start').slice(1),parts=raw.split('/'),p=parts[0]||'start';document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('.links a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+p));if(p==='regionen'&&parts[1]&&DATA.regions){const st=DATA.regions.states.find(x=>x.slug===parts[1]);if(st)showRegion(st.name)}if(p==='reformen'&&parts[1]&&DATA.reforms){selectReform(parts[1].toUpperCase())}window.scrollTo({top:0,behavior:'instant'})}
window.addEventListener('hashchange',route);
function renderCore(){const d=DATA.core;$('brand').textContent=d.brand;$('tagline').textContent=d.tagline;$('goalText').textContent=d.goal;$('pillarGrid').innerHTML=d.pillars.map((x,i)=>`<div class="card"><div class="num">${String(i+1).padStart(2,'0')}</div><h3>${esc(x.name)}</h3><p>${x.binding?'Verbindlicher WERK-Grundsatz.':'Programmpunkt.'}</p></div>`).join('');$('coreLoad').textContent='Datenstand '+d.version}
function cat(r){const a=r.area.toLowerCase();if(a.includes('finanz'))return'finanzen';if(a.includes('verwaltung')||a.includes('staat'))return'staat';if(a.includes('region'))return'regionen';if(a.includes('demokratie'))return'demokratie';return'organisation'}
let reformFilter='alle',reformQuery='',selectedReform='DEBT-01';
function openish(s=''){return /(offen|auszuarbeiten|zu berechnen|zu kalkulieren|prüf|abhängig|szenario)/i.test(String(s))}
function stage(label,value,notNeeded=false){let state='voll';if(notNeeded)state='n/a';else if(!value)state='offen';else if(openish(value))state='teil';return `<div class="stage"><b>${label}</b>${state}</div>`}
function sourceIdsFor(r){if(r.id.startsWith('DEBT'))return['OEBFA-DEBT'];if(r.id.startsWith('REG'))return['BVG-10','BVG-15','BVG-118'];if(r.id.startsWith('DIR'))return['BMI-EVOTE','BVG-10'];if(r.id.startsWith('ORG'))return['PARTG-1','PARTG-2'];return[]}
function sourceLinks(ids){const all=DATA.legal?.sources||[];return ids.map(id=>all.find(s=>s.id===id)).filter(Boolean).map(s=>`<a target="_blank" rel="noopener" href="${s.url}">${esc(s.label)}</a>`).join('')}
function visibleReforms(){return DATA.reforms.reforms.filter(r=>(reformFilter==='alle'||cat(r)===reformFilter)&&(!reformQuery||`${r.id} ${r.title} ${r.area} ${r.goal}`.toLowerCase().includes(reformQuery.toLowerCase())))}
function renderReformList(){const rs=visibleReforms();$('reformList').innerHTML=rs.map(r=>`<button class="reformBtn ${r.id===selectedReform?'active':''}" data-id="${esc(r.id)}"><small>${esc(r.id)} · ${esc(r.area)}</small><b>${esc(r.title)}</b><span>${esc(r.status)}</span></button>`).join('')||'<div class="empty">Keine Reform entspricht diesem Filter.</div>';document.querySelectorAll('.reformBtn').forEach(b=>b.onclick=()=>{selectedReform=b.dataset.id;history.replaceState(null,'','#reformen/'+selectedReform.toLowerCase());renderReformList();renderDecision()});$('reformCount').textContent=`${rs.length} von ${DATA.reforms.reforms.length} Reformen sichtbar`}
function selectReform(id){if(DATA.reforms.reforms.some(r=>r.id===id))selectedReform=id;renderReformList();renderDecision()}
function renderDecision(){const r=DATA.reforms.reforms.find(x=>x.id===selectedReform)||visibleReforms()[0]||DATA.reforms.reforms[0];if(!r)return;selectedReform=r.id;const calc=[r.costs,r.financing,r.impact_1y,r.impact_5y,r.impact_10y].join(' ');const voteNotNeeded=String(r.citizen_vote).toLowerCase()==='nein';$('decision').innerHTML=`<div class="decisionTop"><div class="num">${esc(r.id)} · ${esc(r.area)}</div><h3>${esc(r.title)}</h3><p>${esc(r.goal)}</p><div class="stagebar">${stage('Problem',r.problem)}${stage('Rechnung',calc)}${stage('Recht',r.legal_status)}${stage('Ebene',r.target_level)}${stage('Bürgerentscheid',r.citizen_vote,voteNotNeeded)}${stage('Review',r.review)}</div></div><div class="decisionBody"><div class="facts"><div class="fact"><span>Status</span><b>${esc(r.status)}</b></div><div class="fact"><span>Ebene heute</span><b>${esc(r.current_level)}</b></div><div class="fact"><span>Zielebene</span><b>${esc(r.target_level)}</b></div></div><div class="sectionBlock"><h4>01 · Problem</h4><p>${esc(r.problem)}</p></div><div class="sectionBlock"><h4>02 · Rechnung & Finanzierung</h4><p><b>Kosten:</b> ${esc(r.costs)}</p><p><b>Finanzierung:</b> ${esc(r.financing)}</p><div class="timeline"><div class="time"><span>1 Jahr</span><b>${esc(r.impact_1y)}</b></div><div class="time"><span>5 Jahre</span><b>${esc(r.impact_5y)}</b></div><div class="time"><span>10 Jahre</span><b>${esc(r.impact_10y)}</b></div></div></div><div class="sectionBlock"><h4>03 · Recht & Zuständigkeit</h4><p><b>Rechtsstatus:</b> ${esc(r.legal_status)}</p><p><b>Bürgerentscheid:</b> ${esc(r.citizen_vote)}</p><div class="sourceLinks">${sourceLinks(sourceIdsFor(r))||'<span class="empty">Noch keine zentrale Primärquelle zugeordnet.</span>'}</div></div><div class="sectionBlock"><h4>04 · Erfolgskontrolle</h4><div class="kpis">${r.kpi.map(k=>`<span class="kpi">${esc(k)}</span>`).join('')}</div><p><b>Review:</b> ${esc(r.review)}</p></div></div>`}
function renderReforms(){const filters=[['alle','Alle'],['finanzen','Finanzen'],['staat','Staat'],['regionen','Regionen'],['demokratie','Demokratie'],['organisation','Organisation']];$('filters').innerHTML=filters.map((x,i)=>`<button class="filter ${i===0?'active':''}" data-f="${x[0]}">${x[1]}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{reformFilter=b.dataset.f;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderReformList();const v=visibleReforms();if(v.length&&!v.some(r=>r.id===selectedReform)){selectedReform=v[0].id;renderReformList();renderDecision()}});$('reformSearch').oninput=e=>{reformQuery=e.target.value;renderReformList();const v=visibleReforms();if(v.length&&!v.some(r=>r.id===selectedReform)){selectedReform=v[0].id;renderReformList();renderDecision()}};renderReformList();renderDecision()}
function renderRegions(){$('levels').innerHTML=DATA.regions.levels.map(x=>`<div class="card level"><div class="num">${esc(x.label)}</div><h3>${esc(x.label)}</h3><p>${esc(x.rule)}</p></div>`).join('');$('regionBtns').innerHTML=DATA.regions.states.map((s,i)=>`<button class="regionBtn ${i===0?'active':''}" data-region="${esc(s.name)}" data-slug="${esc(s.slug)}">${esc(s.name)}</button>`).join('');document.querySelectorAll('.regionBtn').forEach(b=>b.onclick=()=>{history.replaceState(null,'','#regionen/'+b.dataset.slug);showRegion(b.dataset.region)});$('centralCheck').innerHTML=DATA.regions.centralisation_check.map(x=>`<li>${esc(x)}</li>`).join('');showRegion(DATA.regions.states[0].name)}
function showRegion(name){const s=DATA.regions.states.find(x=>x.name===name)||DATA.regions.states[0];document.querySelectorAll('.regionBtn').forEach(b=>b.classList.toggle('active',b.dataset.region===s.name));$('regionName').textContent=s.name;$('regionStatus').textContent=s.profile_status+'. Regionale Positionen werden erst nach verifizierter lokaler Ausarbeitung veröffentlicht.';const ps=DATA.partners.states.find(x=>x.name===s.name)?.verified||[];const qs=DATA.votes.questions.filter(q=>q.scope==='Bundesland'&&(q.region==='alle'||q.region===s.name));$('partnerCount').textContent=ps.length;$('regionReformCount').textContent=s.reforms.length;$('regionVoteCount').textContent=qs.length;$('regionVoteList').innerHTML=qs.map(q=>`<div class="card"><div class="num">${esc(q.type)}</div><h3>${esc(q.title)}</h3><p>${esc(q.status)}</p></div>`).join('')||'<span class="empty">Keine regionalen Bürgerfragen.</span>'}
function renderVotes(){$('voteNotice').textContent=DATA.votes.status_notice;$('guardrails').innerHTML=DATA.votes.guardrails.map(x=>`<li>${esc(x)}</li>`).join('');$('digitalStatus').textContent=DATA.votes.digital_status.current+' '+DATA.votes.digital_status.target;$('digitalSource').innerHTML=`<a target="_blank" rel="noopener" href="${DATA.votes.digital_status.source.url}">${esc(DATA.votes.digital_status.source.label)}</a>`;$('voteGrid').innerHTML=DATA.votes.questions.map(q=>`<article class="voteCard"><div class="num">${esc(q.id)}</div><h3>${esc(q.title)}</h3><div class="badges"><span class="badge">${esc(q.scope)}</span><span class="badge">${esc(q.type)}</span><span class="badge">${esc(q.status)}</span></div><p>${esc(q.legal_note)}</p>${q.finance_note?`<p><b>Finanzierung:</b> ${esc(q.finance_note)}</p>`:''}<div class="choices">${q.choices.map(c=>`<button class="choice">${esc(c)}</button>`).join('')}</div><div class="voteMsg">Demo – keine Stimme gespeichert.</div><div class="sourceLinks">${(q.sources||[]).map(s=>`<a target="_blank" rel="noopener" href="${s.url}">${esc(s.label)}</a>`).join('')}</div></article>`).join('');document.querySelectorAll('.voteCard').forEach(card=>card.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{card.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');card.querySelector('.voteMsg').textContent='Ausgewählt: '+b.textContent+' · Demo – keine Stimme gespeichert.'}))}
function renderPartners(){$('partnerNotice').textContent=DATA.partners.public_notice;$('partnerReq').innerHTML=DATA.partners.binding_requirements.map(x=>`<li>${esc(x)}</li>`).join('');$('admission').innerHTML=DATA.partners.admission_process.map(x=>`<li>${esc(x)}</li>`).join('');$('partnerRows').innerHTML=DATA.partners.states.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${s.verified.length?s.verified.map(x=>esc(x.name)).join(', '):'<span class="empty">Noch keine verifizierte Liste veröffentlicht</span>'}</td><td>${s.verified.length?'<span class="statusok">verifiziert</span>':'<span class="statuswarn">Register in Vorbereitung</span>'}</td></tr>`).join('');$('partnerModels').innerHTML=DATA.partners.partner_models.map(x=>`<div class="card"><div class="num">${esc(x.id)}</div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p></div>`).join('')}
function renderTransparency(){const rows=[['core.json','Marke, Tagline, Grundkodex, Säulen',DATA.core.version],['reforms.json','Reformregister, Wirkungsfelder, KPIs',DATA.reforms.version],['regions.json','Bund/Land/Gemeinde, neun Länder, Zentralisierungscheck',DATA.regions.version],['votes.json','Bürgerfragen, Guardrails und digitale Rechtslage',DATA.votes.version],['partners.json','Bürgerlisten-Pakt und verifizierte Partner',DATA.partners.version],['legal.json','Zentrale Primärquellen und Rechtsnotizen',DATA.legal.version]];$('dataRows').innerHTML=rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('');$('legalRows').innerHTML=DATA.legal.sources.map(s=>`<tr><td><b>${esc(s.topic)}</b></td><td><a target="_blank" rel="noopener" href="${s.url}" style="color:var(--cd);text-decoration:underline">${esc(s.label)}</a></td><td>${esc(s.note)}</td></tr>`).join('');$('legalNotice').textContent=DATA.legal.notice}
async function init(){try{[DATA.core,DATA.reforms,DATA.regions,DATA.votes,DATA.partners,DATA.legal]=await Promise.all([getJSON('./werk-data/core.json'),getJSON('./werk-data/reforms.json'),getJSON('./werk-data/regions.json'),getJSON('./werk-data/votes.json'),getJSON('./werk-data/partners.json'),getJSON('./werk-data/legal.json')]);renderCore();renderReforms();renderRegions();renderVotes();renderPartners();renderTransparency();route()}catch(e){console.error(e);document.querySelectorAll('.load').forEach(x=>{x.textContent='Daten konnten nicht geladen werden: '+e.message;x.classList.add('statusbad')})}}
init();route();
