#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MEM = ROOT / "project-memory"
STATUS_FILE = MEM / "PROJECT_STATUS.md"
STATUS_WORDS = ["TODO","IN_PROGRESS","BLOCKED","PARTIAL","IMPLEMENTED","IMPLEMENTED_NOT_VERIFIED","VERIFIED","VERIFIED_NOT_ACCEPTED","ACCEPTED","PRODUCTION_CONFIRMED","DONE","REJECTED","SUPERSEDED","DEFERRED"]

def read(name: str) -> str:
    path = MEM / name
    return path.read_text(encoding="utf-8") if path.exists() else ""

def count_status(text: str) -> dict[str, int]:
    return {k: len(re.findall(rf"\bStatus:\s*{re.escape(k)}\b", text)) for k in STATUS_WORDS if len(re.findall(rf"\bStatus:\s*{re.escape(k)}\b", text))}

def headings(text: str, limit: int = 12) -> list[str]:
    return [line[3:].strip() for line in text.splitlines() if line.startswith("## ") and not line.startswith("## Status")][:limit]

def main() -> None:
    sources = {name: read(name) for name in ["TASK_LEDGER.md","CHANGE_REQUESTS.md","OPEN_LOOPS.md","DEPENDENCIES.md","EVIDENCE.md"]}
    handoff = read("SESSION_HANDOFF.md")
    lines = ["# Project Status", "", "Generated by `scripts/project_memory_status.py`.", "", "## Status counts", ""]
    for name, text in sources.items():
        lines.append(f"### {name}")
        counts = count_status(text)
        if counts:
            lines += [f"- {k}: {v}" for k, v in counts.items()]
        else:
            lines.append("- No explicit status markers found.")
        lines.append("")
    lines += ["## Open loops", ""] + ([f"- {x}" for x in headings(sources.get("OPEN_LOOPS.md", ""))] or ["- None listed."])
    lines += ["", "## Dependencies", ""] + ([f"- {x}" for x in headings(sources.get("DEPENDENCIES.md", ""))] or ["- None listed."])
    lines += ["", "## Latest handoff", "", "\n".join(handoff.splitlines()[:40]).strip() or "No handoff recorded.", ""]
    STATUS_FILE.write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    main()
